import { Post } from "../types/types";

export const posts: Post[] = [
  {
    id: 1,
    imageUrl: "images/post-image1.png",
    category: "TOURISM",
    title: "Exploring Ancient Rome",
    author: "Kate Willems",
    date: "October 26, 2023",
  },
  {
    id: 2,
    imageUrl: "images/post-image2.png",
    category: "SPORT",
    title: "Marathon Training Tips",
    author: "Kate Willems",
    date: "October 27, 2023",
  },
  {
    id: 3,
    imageUrl: "images/post-image3.png",
    category: "FASHION",
    title: "Spring's Top Color Trends",
    author: "Kate Willems",
    date: "October 28, 2023",
  },
  {
    id: 4,
    imageUrl: "images/post-image4.png",
    category: "FASHION",
    title: "Eco-Friendly Fashion Brands",
    author: "Kate Willems",
    date: "October 29, 2023",
  },
  {
    id: 5,
    imageUrl: "images/post-image5.png",
    category: "CLOTHES",
    title: "The Best Denim for Your Shape",
    author: "Kate Willems",
    date: "October 30, 2023",
  },
  {
    id: 6,
    imageUrl: "images/post-image6.png",
    category: "TOURISM",
    title: "Budget-Friendly Travel Destinations",
    author: "Kate Willems",
    date: "October 31, 2023",
  },
  {
    id: 7,
    imageUrl: "images/feat-post-main.png",
    category: "TOURISM",
    title: "The Northern Lights Adventure",
    author: "Kate Willems",
    date: "November 1, 2023",
    featured: true,
    content:
      "Experience the magic of the aurora borealis in a breathtaking Arctic expedition.",
  },
  {
    id: 8,
    imageUrl: "images/post-image3.png",
    category: "TOURISM",
    title: "Hidden Gems of the Mediterranean",
    author: "Kate Willems",
    date: "October 26, 2023",
  },
  {
    id: 9,
    imageUrl: "images/post-image4.png",
    category: "SPORT",
    title: "Breaking Records: Olympic Highlights",
    author: "Kate Willems",
    date: "October 26, 2023",
  },
  {
    id: 10,
    imageUrl: "images/post-image5.png",
    category: "FASHION",
    title: "Runway Trends for the Upcoming Season",
    author: "Kate Willems",
    date: "October 26, 2023",
  },
  {
    id: 11,
    imageUrl: "images/post-image6.png",
    category: "FASHION",
    title: "The Evolution of Street Style",
    author: "Kate Willems",
    date: "October 26, 2023",
  },

  {
    id: 12,
    imageUrl: "images/post-image1.png",
    category: "SPORT",
    title: "The Rise of Esports",
    author: "Kate Willems",
    date: "November 2, 2023",
  },
  {
    id: 13,
    imageUrl: "images/post-image2.png",
    category: "FASHION",
    title: "Vintage Style Revival",
    author: "Kate Willems",
    date: "November 3, 2023",
  },
  {
    id: 14,
    imageUrl: "images/post-image3.png",
    category: "TOURISM",
    title: "A Guide to Sustainable Travel",
    author: "Kate Willems",
    date: "November 4, 2023",
  },
  {
    id: 15,
    imageUrl: "images/post-image4.png",
    category: "CLOTHES",
    title: "Finding the Perfect Suit",
    author: "Kate Willems",
    date: "November 5, 2023",
  },
  {
    id: 16,
    imageUrl: "images/post-image5.png",
    category: "SPORT",
    title: "Local Soccer Clubs to Watch",
    author: "Kate Willems",
    date: "November 6, 2023",
  },
  {
    id: 17,
    imageUrl: "images/post-image6.png",
    category: "TOURISM",
    title: "Top 10 City Breaks in Europe",
    author: "Kate Willems",
    date: "November 7, 2023",
  },
  {
    id: 18,
    imageUrl: "images/post-image1.png",
    category: "FASHION",
    title: "The Best Streetwear Collaborations",
    author: "Kate Willems",
    date: "November 8, 2023",
  },
  {
    id: 19,
    imageUrl: "images/post-image2.png",
    category: "CLOTHES",
    title: "The Return of the Flannel",
    author: "Kate Willems",
    date: "November 9, 2023",
  },
  {
    id: 20,
    imageUrl: "images/post-image3.png",
    category: "SPORT",
    title: "Women in Competitive Sports",
    author: "Kate Willems",
    date: "November 10, 2023",
  },
  {
    id: 21,
    imageUrl: "images/post-image4.png",
    category: "TOURISM",
    title: "Discovering the Pyramids of Egypt",
    author: "Kate Willems",
    date: "November 11, 2023",
  },
  {
    id: 22,
    imageUrl: "images/post-image5.png",
    category: "FASHION",
    title: "The Ultimate Accessory Guide",
    author: "Kate Willems",
    date: "November 12, 2023",
  },
  {
    id: 23,
    imageUrl: "images/post-image6.png",
    category: "CLOTHES",
    title: "The Rise of Athleisure",
    author: "Kate Willems",
    date: "November 13, 2023",
  },
  {
    id: 24,
    imageUrl: "images/post-image1.png",
    category: "SPORT",
    title: "CrossFit: A Community Phenomenon",
    author: "Kate Willems",
    date: "November 14, 2023",
  },
  {
    id: 25,
    imageUrl: "images/post-image2.png",
    category: "TOURISM",
    title: "Exploring the Amazon Rainforest",
    author: "Kate Willems",
    date: "November 15, 2023",
  },
];
